var searchData=
[
  ['variablespeedringbuffer_0',['VariableSpeedRingBuffer',['../classaudio__tools_1_1_variable_speed_ring_buffer.html',1,'audio_tools']]],
  ['variablespeedringbuffer180_1',['VariableSpeedRingBuffer180',['../classaudio__tools_1_1_variable_speed_ring_buffer180.html',1,'audio_tools']]],
  ['variablespeedringbuffer_3c_20int16_5ft_20_3e_2',['VariableSpeedRingBuffer&lt; int16_t &gt;',['../classaudio__tools_1_1_variable_speed_ring_buffer.html',1,'audio_tools']]],
  ['variablespeedringbuffersimple_3',['VariableSpeedRingBufferSimple',['../classaudio__tools_1_1_variable_speed_ring_buffer_simple.html',1,'audio_tools']]],
  ['vban_4',['VBan',['../struct_v_ban.html',1,'']]],
  ['vbanconfig_5',['VBANConfig',['../classaudio__tools_1_1_v_b_a_n_config.html',1,'audio_tools']]],
  ['vbanheader_6',['VBanHeader',['../struct_v_ban_header.html',1,'']]],
  ['vbanstream_7',['VBANStream',['../classaudio__tools_1_1_v_b_a_n_stream.html',1,'audio_tools']]],
  ['vector_8',['Vector',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aabstractsynthesizerchannel_20_2a_20_3e_9',['Vector&lt; audio_tools::AbstractSynthesizerChannel * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aallocsize_20_3e_10',['Vector&lt; audio_tools::AllocSize &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aaudioactions_3a_3aaction_20_2a_20_3e_11',['Vector&lt; audio_tools::AudioActions::Action * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aaudioeffect_20_2a_20_3e_12',['Vector&lt; audio_tools::AudioEffect * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aaudioinfosupport_20_2a_20_3e_13',['Vector&lt; audio_tools::AudioInfoSupport * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aaudiooutput_20_2a_20_3e_14',['Vector&lt; audio_tools::AudioOutput * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aavistreamheader_20_3e_15',['Vector&lt; audio_tools::AVIStreamHeader &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3abasebuffer_3c_20frame_20_3e_20_2a_20_3e_16',['Vector&lt; audio_tools::BaseBuffer&lt; Frame &gt; * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3abasebuffer_3c_20t_20_3e_20_2a_20_3e_17',['Vector&lt; audio_tools::BaseBuffer&lt; T &gt; * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3abasebuffer_3c_20uint8_5ft_20_3e_20_2a_20_3e_18',['Vector&lt; audio_tools::BaseBuffer&lt; uint8_t &gt; * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3abaseconverter_20_2a_20_3e_19',['Vector&lt; audio_tools::BaseConverter * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3achannelsplitoutput_3a_3achannelselectionoutputdef_20_3e_20',['Vector&lt; audio_tools::ChannelSplitOutput::ChannelSelectionOutputDef &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3achannelsselectoutput_3a_3achannelselectionoutputdef_20_3e_21',['Vector&lt; audio_tools::ChannelsSelectOutput::ChannelSelectionOutputDef &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3acodecfactory_3a_3adecoderfactoryline_20_3e_22',['Vector&lt; audio_tools::CodecFactory::DecoderFactoryLine &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3acodecfactory_3a_3aencoderfactoryline_20_3e_23',['Vector&lt; audio_tools::CodecFactory::EncoderFactoryLine &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3ainputmerge_3a_3amergerecord_20_3e_24',['Vector&lt; audio_tools::InputMerge::MergeRecord &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aint24_5f4bytes_5ft_20_3e_25',['Vector&lt; audio_tools::int24_4bytes_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3akaradioprotocol_3a_3aaction_20_3e_26',['Vector&lt; audio_tools::KARadioProtocol::Action &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3amedianfilter_3a_3amediannode_5ft_20_3e_27',['Vector&lt; audio_tools::MedianFilter::MedianNode_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3amimedetector_3a_3acheck_20_3e_28',['Vector&lt; audio_tools::MimeDetector::Check &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3amodifyingstream_20_2a_20_3e_29',['Vector&lt; audio_tools::ModifyingStream * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3amultidecoder_3a_3adecoderinfo_20_3e_30',['Vector&lt; audio_tools::MultiDecoder::DecoderInfo &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3apininfoesp32_20_3e_31',['Vector&lt; audio_tools::PinInfoESP32 &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3aqueuelockfree_3a_3anode_20_3e_32',['Vector&lt; audio_tools::QueueLockFree::Node &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3asoundgenerator_3c_20t_20_3e_20_2a_20_3e_33',['Vector&lt; audio_tools::SoundGenerator&lt; T &gt; * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3astr_20_3e_34',['Vector&lt; audio_tools::Str &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3astream_20_2a_20_3e_35',['Vector&lt; audio_tools::Stream * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3atflitemicrospeechrecognizecommands_3a_3aresult_20_3e_36',['Vector&lt; audio_tools::TfLiteMicroSpeechRecognizeCommands::Result &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20audio_5ftools_3a_3avfs_20_2a_20_3e_37',['Vector&lt; audio_tools::VFS * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20bool_20_3e_38',['Vector&lt; bool &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20char_20_3e_39',['Vector&lt; char &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20const_20char_20_2a_20_3e_40',['Vector&lt; const char * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20crgb_20_3e_41',['Vector&lt; CRGB &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20effect_5ft_20_3e_42',['Vector&lt; effect_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20entry_20_3e_43',['Vector&lt; Entry &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20flac_5f_5fint32_20_3e_44',['Vector&lt; FLAC__int32 &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20float_20_3e_45',['Vector&lt; float &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20ggwave_5fprotocolid_20_3e_46',['Vector&lt; ggwave_ProtocolId &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20int_20_3e_47',['Vector&lt; int &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20int16_5ft_20_3e_48',['Vector&lt; int16_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20int32_5ft_20_3e_49',['Vector&lt; int32_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20int8_5ft_20_3e_50',['Vector&lt; int8_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20kiss_5ffft_5fcpx_20_3e_51',['Vector&lt; kiss_fft_cpx &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20mbed_3a_3apwmout_20_2a_20_3e_52',['Vector&lt; mbed::PwmOut * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20mp3d_5fsample_5ft_20_3e_53',['Vector&lt; mp3d_sample_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20mtsstreamtype_20_3e_54',['Vector&lt; MTSStreamType &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20pwmout_20_2a_20_3e_55',['Vector&lt; PwmOut * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20pwmpin_20_3e_56',['Vector&lt; PWMPin &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20sample_20_3e_57',['Vector&lt; Sample &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20streamcontenttype_20_3e_58',['Vector&lt; StreamContentType &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20tsdpmtstreamtype_20_3e_59',['Vector&lt; TSDPMTStreamType &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20uint16_5ft_20_3e_60',['Vector&lt; uint16_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20uint8_5ft_20_3e_61',['Vector&lt; uint8_t &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vector_3c_20void_20_2a_20_3e_62',['Vector&lt; void * &gt;',['../classaudio__tools_1_1_vector.html',1,'audio_tools']]],
  ['vfs_63',['VFS',['../classaudio__tools_1_1_v_f_s.html',1,'audio_tools']]],
  ['vfs_5flittlefs_64',['VFS_LittleFS',['../classaudio__tools_1_1_v_f_s___little_f_s.html',1,'audio_tools']]],
  ['vfs_5fmulti_65',['VFS_Multi',['../classaudio__tools_1_1_v_f_s___multi.html',1,'audio_tools']]],
  ['vfs_5fsdmmc_66',['VFS_SDMMC',['../classaudio__tools_1_1_v_f_s___s_d_m_m_c.html',1,'audio_tools']]],
  ['vfs_5fsdspi_67',['VFS_SDSPI',['../classaudio__tools_1_1_v_f_s___s_d_s_p_i.html',1,'audio_tools']]],
  ['vfs_5fspffs_68',['VFS_SPFFS',['../classaudio__tools_1_1_v_f_s___s_p_f_f_s.html',1,'audio_tools']]],
  ['vfsfile_69',['VFSFile',['../classaudio__tools_1_1_v_f_s_file.html',1,'audio_tools']]],
  ['videoaudiobufferedsync_70',['VideoAudioBufferedSync',['../classaudio__tools_1_1_video_audio_buffered_sync.html',1,'audio_tools']]],
  ['videoaudiosync_71',['VideoAudioSync',['../classaudio__tools_1_1_video_audio_sync.html',1,'audio_tools']]],
  ['videooutput_72',['VideoOutput',['../classaudio__tools_1_1_video_output.html',1,'audio_tools']]],
  ['volumecontrol_73',['VolumeControl',['../classaudio__tools_1_1_volume_control.html',1,'audio_tools']]],
  ['volumemeter_74',['VolumeMeter',['../classaudio__tools_1_1_volume_meter.html',1,'audio_tools']]],
  ['volumestream_75',['VolumeStream',['../classaudio__tools_1_1_volume_stream.html',1,'audio_tools']]],
  ['volumestreamconfig_76',['VolumeStreamConfig',['../structaudio__tools_1_1_volume_stream_config.html',1,'audio_tools']]],
  ['volumesupport_77',['VolumeSupport',['../classaudio__tools_1_1_volume_support.html',1,'audio_tools']]],
  ['vorbisdecoder_78',['VorbisDecoder',['../classaudio__tools_1_1_vorbis_decoder.html',1,'audio_tools']]],
  ['vs1053config_79',['VS1053Config',['../classaudio__tools_1_1_v_s1053_config.html',1,'audio_tools']]],
  ['vs1053stream_80',['VS1053Stream',['../classaudio__tools_1_1_v_s1053_stream.html',1,'audio_tools']]]
];
