/**
 * @file usb-device-tx-callback.ino
 * @brief USB Audio TX using USBAudioDevice directly with a callback.
 *
 * This example shows the lower-level API: instead of using USBAudioStream,
 * the application registers a TX callback directly on USBAudioDevice and
 * drives the pump loop itself.  USBAudioDevice is a platform alias — it
 * resolves to USBAudioDeviceTinyUSB (RP2040) or USBAudioDeviceESP32
 * automatically via the USBAudioDevice.h dispatch header.
 *
 * TX callback (device → host, i.e. microphone / capture):
 *   Called by process() each millisecond to fill one USB isochronous packet.
 *   The example feeds a sine wave generated by AudioTools.
 *
 * @note this example is more efficient than usb-tx.ino because it avoids the
 * overhead of the USBAudioStream layer, but it also requires more manual
 * handling of the USB stack and audio generation.
 * @author Phil Schatzmann
 * @copyright GPLv3
 */
#include "AudioTools.h"
#include "AudioTools/Sandbox/USB/USBAudioDevice.h"

// ── Audio source ─────────────────────────────────────────────────────────────
SineGenerator<int16_t> sine(32000);
GeneratedSoundStream<int16_t> sound(sine);

// ── USB device ───────────────────────────────────────────────────────────────
USBAudioDevice dev;

// ── TX callback: fill each USB packet with sine audio ────────────────────────
uint16_t onTx(uint8_t* data, uint16_t len) {
  return (uint16_t)sound.readBytes(data, len);
}

void setup() {
  Serial.begin(115200);
  AudioToolsLogger.begin(Serial, AudioToolsLogLevel::Info);

  USBAudioConfig cfg = dev.defaultConfig(TX_MODE);
  cfg.sample_rate = 44100;
  cfg.channels = 2;
  cfg.bits_per_sample = 16;

  sine.begin(cfg, N_B4);

  dev.setTxCallback(onTx);
  dev.begin(cfg);  // begin() calls beginUSB() internally
}

void loop() {
  dev.process();  // drives tud_task() on TinyUSB platforms + TX callback → USB FIFO
}
