#pragma once
// include to identify future compile errors: if you don't have all dependencies
// installed this will generate compile errors!
#include "A2DPStream.h"
#include "AudioBoardStream.h"
#include "AudioClientRTSP.h"
#include "AudioESP32ULP.h"
#include "AudioEffectsSuite.h"
#include "AudioFFT.h"
#include "AudioKissFFT.h"
#include "AudioSTK.h"
#include "Concurrency.h"
#include "FFTEffects.h"
#include "HLSStream.h"
#include "I2SCodecStream.h"
#include "LEDOutput.h"
#include "MaximilianDSP.h"
#include "MemoryManager.h"
#include "PIDController.h"
#include "R2ROutput.h"
#include "RTSP.h"
#include "SPDIFOutput.h"
#include "StdioStream.h"
#include "TfLiteAudioStream.h"
#include "VBANStream.h"
#include "VS1053Stream.h"
//  #include "MozziStream.h"
//  #include "AudioServerEx.h"
//  #include "WM8960Stream.h" // driver part of AudioBoardStream
//  #include "AudioFaust.h"
//  #include "PureDataStream.h"
//  #include "Jupyter.h"
//  #include "PortAudioStream.h"
//  #include "MiniAudioStream.h"
//  #include "AudioCmsisFFT.h"
//  #include "AudioRealFFT.h"
//  #include "AudioESP32FFT.h"
//  #include "AudioEspressifFFT.h"
//  #include "LEDOutputUnoR4.h"
//  #include "AudioMP34DT05.h"
//  #include "AudioESP8266.h"
//  #include "FFTDisplay.h"
//  #include "AudioKit.h" // obsolete
