// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// i2s_slave_in //
// ------------ //

#define i2s_slave_in_wrap_target 2
#define i2s_slave_in_wrap 6

#define i2s_slave_in_offset_write 6u

static const uint16_t i2s_slave_in_program_instructions[] = {
    0x20a2, //  0: wait   1 pin, 2                   
    0x2022, //  1: wait   0 pin, 2                   
            //     .wrap_target
    0x20a1, //  2: wait   1 pin, 1                   
    0x4001, //  3: in     pins, 1                    
    0x2021, //  4: wait   0 pin, 1                   
    0x0002, //  5: jmp    2                          
    0x8020, //  6: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_slave_in_program = {
    .instructions = i2s_slave_in_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config i2s_slave_in_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_slave_in_wrap_target, offset + i2s_slave_in_wrap);
    return c;
}
#endif

